server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE:form_weaver}
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

logging:
  level:
    org.springframework.data.mongodb: debug
